# Temporary Build Image
FROM php:8.0.2-fpm-alpine as build-container

RUN apk update
RUN apk add wget unzip

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY --chown=www-data:www-data . /var/www/app

# Make the app the pwd
WORKDIR /var/www/app

RUN composer install --ignore-platform-reqs --no-scripts --no-autoloader

CMD ["php","artisan","serve","--host","0.0.0.0"]